# Generated by Django 5.0.2 on 2024-11-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=400)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RunSQL(
            """CREATE TABLE api_pageembedding (
                    id bigint(20) NOT NULL AUTO_INCREMENT,
                    embedding longblob NOT NULL,
                    page_id bigint(20) NOT NULL,
                    PRIMARY KEY (`id`),
                    KEY `api_pageembedding_page_id_0bdf5fff_fk_api_page_id` (`page_id`),
                    VECTOR KEY `vector_index` (`embedding`),
                    CONSTRAINT `api_pageembedding_page_id_0bdf5fff_fk_api_page_id`
                        FOREIGN KEY (`page_id`)
                        REFERENCES `api_page` (`id`));
                """
        ),
    ]
